name = "rhystmorgan/multisig"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'rhystmorgan/multisig'"

[repository]
user = "rhystmorgan"
project = "multisig"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
